Combined branch
Ecdar-SW5/Ecdar-GUI pull request #124
Opened 2022-12-07 13:01 UTC by EmilieSonne

This issue contains final changes to simulation and reachability checks. 
It solves the following issues: fixes #103 , fixes #128 , fixes #123 , fixes #107 , fixes #101 , fixes #102 , fixes #99 , fixes #97 ish ;), fixes #92 and fixes #135.

In plain text, we are now able to make a reachability check from current locations (in the simulation view, where stepping changes the state). Clocks are not taken into consideration as the simulation results are not compatible with the expected input from the reachability part. The trace/path resulting from a successful reachability check is highlighted in a deep purple color. 

Improvements to the simulation view are that it now displays the clock values in the trace, and it is possible to jump between different states without loosing the trace history. It is also possible to get clocks by pressing the small symbol in the top right corner in the simulation view now. 

On a more general note, we have also tried to conquer the use of static/global properties. (den her går ud til Sigurd)

Finally, test cases have been added to the simulation view. 

We wish you good luck. Ses til julefrukost (husk at tilmelde jer please).

2022-12-08 08:04 UTC, mksm20 requested changes
Se kommentarer, ser fornuftigt ud!

2022-12-08 10:42 UTC, jhbengtsson commented on src/main/java/ecdar/controllers/EcdarController.java
> +            // scaling.selectToggle(scaleM); // Necessary to avoid project pane appearing off-screen
upsi, den er væk nu :)

2022-12-08 10:51 UTC, jhbengtsson commented on src/main/java/ecdar/abstractions/BackendInstance.java
> +        setIsThreadSafe(true);
den er fjernet nu

2022-12-08 11:08 UTC, mksm20 approved these changes
lgtm

2022-12-09 09:11 UTC, Mightyhaha approved these changes
LGTM, Ses til juleFRUkost

2022-12-09 11:07 UTC, merged